version: 0.0.{build}
image: Visual Studio 2015
platform:
  - Win32
  - x64
install:
  - git submodule update --init --recursive
build:
  project: Source\code.sln
  parallel: true
  verbosity: minimal
test: off
deploy: off