version: 0.0.{build}
image: Visual Studio 2015
configuration: Release
platform:
  - x86
  - x64
install:
  - git submodule update --init --recursive
build:
  project: Source\code.sln
  parallel: true
  verbosity: minimal