#pragma once

#define SE_ENGINE_NAME "Sapphire Engine"

#define SE_ENGINE_VERSION_MAJOR 0
#define SE_ENGINE_VERSION_MINOR 0
#define SE_ENGINE_VERSION_PATCH 1

#define SE_ENGINE_VERSION_STRING                      \
            SE_STRINGIZE(SE_ENGINE_VERSION_MAJOR) "." \
            SE_STRINGIZE(SE_ENGINE_VERSION_MINOR) "." \
            SE_STRINGIZE(SE_ENGINE_VERSION_PATCH)